### ISSUE TITLE
Making the request serialisation to the apigateway is throwing.

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/p_software_engineering_2#24]
NJI24PSN:00000001]
[21:12:36 INF] Executed endpoint '/identity/sign-in HTTP: POST'
[21:12:36 INF] Request finished in 201.7315ms 200 
[21:14:17 INF] Request starting HTTP/1.1 POST http://localhost:5000/identity/sign-in application/json; charset=utf-8 46
[21:14:17 INF] Executing endpoint '/identity/sign-in HTTP: POST'
[21:14:17 INF] Sending HTTP POST request to: http://localhost:5004/sign-in [Trace ID: 0HN26NJI24PSO:00000001]
[21:14:17 INF] Executed endpoint '/identity/sign-in HTTP: POST'
[21:14:17 ERR] The format of value 'application/json; charset=utf-8' is invalid.
System.FormatException: The format of value 'application/json; charset=utf-8' is invalid.
   at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.Headers.MediaTypeHeaderValue..ctor(String mediaType)
   at Ntrada.Handlers.DownstreamHandler.GetHttpContent(ExecutionData executionData)
   at Ntrada.Handlers.DownstreamHandler.SendRequestAsync(ExecutionData executionData)
   at Ntrada.Handlers.DownstreamHandler.HandleAsync(HttpContext context, RouteConfig config)
   at Ntrada.Requests.RequestHandlerManager.HandleAsync(String handler, HttpContext context, RouteConfig routeConfig)
   at Ntrada.Routing.RouteProvider.Handle(HttpContext context, RouteConfig routeConfig)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Ntrada.Extensions.Tracing.JaegerHttpMiddleware.Invoke(HttpContext context, ITracer tracer)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Ntrada.Extensions.CustomErrors.ErrorHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[21:14:17 INF] Request finished in 19.9699ms 400 application/json

**Comment by SaintAngeLs** [comment]
This issue has been resolved with passing the plain text instead.
